ECertAssessment.MVC/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using ECertAssessment.MVC.API.Service;
using ECertAssessment.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ECertAssessment.MVC.Controllers
{
    
    public class CategoryController : Controller
    {
        private readonly CategoryService  _categoryService;
        private readonly INotyfService _notyf;
       
        public CategoryController(INotyfService notyfService)
        {
            _categoryService = new CategoryService();
            _notyf = notyfService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> GetData()
        {
            var token = Request.Cookies["token"];
            var Categorys = await _categoryService.GetAllCategories(token);
            if (Categorys.ResponseType > 0)
            {
                return Json(new { data = Categorys.ResponseObject });
            }
            else
            {
                return Json(new { data = Categorys.ResponseObject });
            }


        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CategoryModel  category)
        {
            Regex regexObj = new Regex(@"^[A-Z]{3}\d{3}$", RegexOptions.Multiline);
           var foundMatch = regexObj.IsMatch(category.CategoryCode);
            if (!foundMatch)
            {
                _notyf.Error("Invalid Category");
                return View();
            }
            var userId = Request.Cookies["userId"];
            var token = Request.Cookies["token"];
            category.CreatedBy = Convert.ToInt32(userId);
            var _category = await _categoryService.AddCategory(category,token);
            if (_category.ResponseType > 0)
            {
                return Redirect("Index");
            }
            _notyf.Error("Error Occured");
            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            var token = Request.Cookies["token"];
            var model = await _categoryService.GetAllCategoryById(id,token);

            return View(model.ResponseObject);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CategoryModel category)
        {
            var token = Request.Cookies["token"];
            Regex regexObj = new Regex(@"^[A-Z]{3}\d{3}$", RegexOptions.Multiline);
            var foundMatch = regexObj.IsMatch(category.CategoryCode);
            if (!foundMatch)
            {
                _notyf.Error("Invalid Category");
                return View();
            }
            var _category = await _categoryService.UpdateCategory(category,token);
            if (_category.ResponseType > 0)
            {
                return Redirect("Index");
            }

            _notyf.Error("Error Occured");
            return View();
        }
    }
}

ECertAssessment.MVC/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ECertAssessment.MVC.API.Service;
using ECertAssessment.MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MimeKit;

namespace ECertAssessment.MVC.Controllers
{
    public class FileController : Controller
    {
        private readonly FileService _fileService;
        private readonly CategoryService  _categoryService;
        public FileController()
        {
            _fileService = new FileService();
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> GetData()
        {
            var request = new ApiRequest{ Start = 1, Length = 10 };
            var token = Request.Cookies["token"];
            var Files = await _fileService.GetAllFiles(token);
            if (Files.ResponseType > 0)
            {
                return Json(new { data = Files.ResponseObject });
            }
            else
            {
                return Json(new { data = Files.ResponseObject });
            }


        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create( IFormFile file)
        {
            var File = new FileModel();
            var userId = Request.Cookies["userId"];
            var token = Request.Cookies["token"];
            if (file != null && file.Length > 0)
            {
                var filename = file.FileName;
                using (var fileStream = file.OpenReadStream())
                using (var ms = new MemoryStream())
                {
                    fileStream.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    File.File1 = Convert.ToBase64String(fileBytes);
                    File.FileName = filename;
                }


                File.CreateBy = Convert.ToInt32(userId);
                var _File = await _fileService.AddFile(File, token);
                if (_File.ResponseType > 0)
                {
                    return Redirect("Index");
                }
            }

            return View();
        }
        public async Task<FileResult> DownloadFile(int id)
        {
            var token = Request.Cookies["token"];
            var file = await _fileService.GetFileById(id,token);
            if (file != null) {
                var filedata = Convert.FromBase64String(file.ResponseObject.File1);
                return File(filedata, MimeTypes.GetMimeType(file.ResponseObject.FileName), file.ResponseObject.FileName);
            }
            return null;
        }
    }
}

ECertAssessment.MVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ECertAssessment.MVC.API.Service;
using ECertAssessment.MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static ECertAssessment.MVC.Models.DTParameters;

namespace ECertAssessment.MVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductService _productService;
        private readonly CategoryService  _categoryService;
        public ProductController()
        {
            _productService = new ProductService();
            _categoryService = new CategoryService();
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> GetData([FromBody] DtParameters dtParameters)
        {

            var start = dtParameters.start;
            var token = Request.Cookies["token"];
            var products = await _productService.GetAllProducts(token , start);
            if (products.ResponseType > 0)
            {
                   return Json(new
                {
                    draw = dtParameters.draw,
                    recordsTotal = products.NumberOfProducts,
                    recordsFiltered = products.NumberOfProducts,
                       data = products.ResponseObject
                   });
            }
            else
            {
                return Json(new { data = products.ResponseObject });
            }


        }
        public async Task<IActionResult> Create()
        {
            var token = Request.Cookies["token"];
            var request = new ApiRequest { Start = 1, Length = 10 };
            var _category = await _categoryService.GetAllCategories(token);
            if (_category != null)
            {
                ViewBag.Category = _category.ResponseObject.Select(tier => new SelectListItem
                {
                    Text = tier.Name,
                    Value = tier.CategoryId.ToString()
                });
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProductModel  product , IFormFile file)
        {
            var userId = Request.Cookies["userId"];
            var token = Request.Cookies["token"];
            if (file != null && file.Length > 0)
            {
                var filename = file.FileName;
                product.CategoryId = 1;
                using (var fileStream = file.OpenReadStream())
                using (var ms = new MemoryStream())
                {
                    fileStream.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    product.Image = Convert.ToBase64String(fileBytes,0,fileBytes.Length);
                }

            }
            product.CreatedBy = Convert.ToInt32(userId);
            var _product = await _productService.AddProduct(product, token);
            if (_product.ResponseType > 0)
            {
                return Redirect("Index");
            }

            var _category = await _categoryService.GetAllCategories(token);
            ViewBag.Category = _category.ResponseObject.Select(tier => new SelectListItem
            {
                Text = tier.Name,
                Value = tier.CategoryId.ToString()
            });
            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            var request = new ApiRequest { Start = 1, Length = 10 };
            var token = Request.Cookies["token"];
            var _category = await _categoryService.GetAllCategories(token);
            if (_category != null)
            {
                ViewBag.Category = _category.ResponseObject.Select(tier => new SelectListItem
                {
                    Text = tier.Name,
                    Value = tier.CategoryId.ToString()
                });
            }
            var model = await _productService.GetAllProductById(id,token);

            return View(model.ResponseObject);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProductModel product)
        {
            var token = Request.Cookies["token"];
            var userId = Request.Cookies["userId"];
            product.CreatedBy = Convert.ToInt32(userId);
            var _product = await _productService.UpdateProduct(product,token);
            if (_product.ResponseType > 0)
            {
                return Redirect("Index");
            }


            return View();
        }

        public class ByteArrayConverter : System.Text.Json.Serialization.JsonConverter<byte[]>
        {
            public override byte[] Read(ref System.Text.Json.Utf8JsonReader reader, Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
            {
                short[] sByteArray = System.Text.Json.JsonSerializer.Deserialize<short[]>(ref reader);
                byte[] value = new byte[sByteArray.Length];
                for (int i = 0; i < sByteArray.Length; i++)
                {
                    value[i] = (byte)sByteArray[i];
                }

                return value;
            }

            public override void Write(System.Text.Json.Utf8JsonWriter writer, byte[] value, System.Text.Json.JsonSerializerOptions options)
            {
                writer.WriteStartArray();

                foreach (var val in value)
                {
                    writer.WriteNumberValue(val);
                }

                writer.WriteEndArray();
            }
        }
    }
}

ECertAssessment.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECertAssessment.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECertAssessment.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Add User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Index">Product File</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ECertAssessment.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/datatables/datatables.js"></script>
    <script src="~/lib/datatables/datatables.bootstrap4.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>